function prom_notas(){
    var not1=parseInt(document.getElementById("not1").value);
    var not2=parseInt(document.getElementById("not2").value);
    var not3=parseInt(document.getElementById("not3").value);
    var prom= 0;
    prom=((not1+not2+not3)/3)
    document.getElementById("prome").value =prom;
}
/*function prom_notas() {
    var not1 = parseInt(document.getElementById("not1").value);
    var not2 = parseInt(document.getElementById("not2").value);
    var not3 = parseInt(document.getElementById("not3").value);
    var prom = (not1 + not2 + not3) / 3;
    document.getElementById("prome").value = prom;
  }*/

function validarF(){



}


